FROM nvidia/vulkan:1.3-470

ENV TZ Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-key adv --fetch-keys "https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub"

RUN apt-get update && \
    apt-get install -y \
    wget vim tar git cmake build-essential python3.8 python3-pip python3.8-dev python3.8-distutils

RUN pip3 install --upgrade pip

RUN pip3 install --user numpy pygame && pip install --user numpy pygame

WORKDIR /workspace

RUN wget --progress=dot:giga https://carla-releases.s3.us-east-005.backblazeb2.com/Linux/CARLA_0.9.14.tar.gz && \
    tar -xvf CARLA_0.9.14.tar.gz && \
    rm CARLA_0.9.14.tar.gz

RUN packages='libsdl2-2.0 xserver-xorg libvulkan1 libomp5' && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y $packages --no-install-recommends

RUN pip3 install carla
RUN apt-get install -y libomp5 mesa-vulkan-drivers
WORKDIR /workspace
RUN chmod +x /workspace/CarlaUE4/Binaries/Linux/CarlaUE4-Linux-Shipping

RUN packages='libsdl2-2.0 xserver-xorg libvulkan1' \
	&& apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y $packages --no-install-recommends \
    && VULKAN_API_VERSION=`dpkg -s libvulkan1 | grep -oP 'Version: [0-9|\.]+' | grep -oP '[0-9|\.]+'` && \
	mkdir -p /etc/vulkan/icd.d/ && \
	echo \
	"{\
		\"file_format_version\" : \"1.0.0\",\
		\"ICD\": {\
			\"library_path\": \"libGLX_nvidia.so.0\",\
			\"api_version\" : \"${VULKAN_API_VERSION}\"\
		}\
	}" > /etc/vulkan/icd.d/nvidia_icd.json \
	&& rm -rf /var/lib/apt/lists/*

COPY carla.sh carla.sh
RUN chmod +x carla.sh
RUN useradd -m carla
USER carla

ENTRYPOINT ["bash", "./carla.sh"]
